logging:
  level:
    org.springframework.security: error

server:
  port: 8080
spring:
  application:
    name: demo_resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

custom:
  base-url: http://localhost:8080

