server:
  port: 8090
spring:
  application:
    name: demo_client
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
        registration:
          reg-client:
            provider: spring
            client-id: demo_client
            client-secret: "client_secret"
#            client-secret: "secret"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid

logging:
  level:
    org:
      springframework:
        web=DEBUG:
        security: trace